// =============================================================================
// Parameters TEMPLATE - Azure PaaS Workshop (Development / Cost-Optimized)
// =============================================================================
// This is a TEMPLATE file. Do NOT edit this file directly with your values.
//
// INSTRUCTIONS:
// 1. Copy this file to dev.local.bicepparam (which is gitignored)
//    cp dev.bicepparam dev.local.bicepparam
// 2. Fill in your specific values (Entra IDs, passwords)
// 3. Deploy with:
//    az deployment group create \
//      --resource-group rg-blogapp-dev \
//      --template-file main.bicep \
//      --parameters dev.local.bicepparam
//
// This dev template uses cost-optimized settings:
// - Skips Application Gateway (~$250/month savings)
// - Uses smaller Cosmos DB tier (M25 vs M30)
// - Uses B1 App Service tier
// =============================================================================

using 'main.bicep'

// =============================================================================
// Required Parameters
// =============================================================================

param location = 'japanwest'
param environment = 'dev'
param baseName = 'blogapp'

// =============================================================================
// Multi-Group Workshop Support (Optional)
// =============================================================================
// For workshops with multiple groups (A-J) deploying to the same subscription:
// 1. Each group should use a unique resource group name
// 2. Set groupId to your assigned group letter (A-J)
// 3. Create resource group: rg-blogapp-{groupId}-dev
//
// Example for Group C:
//   param groupId = 'C'
//   az group create --name rg-blogapp-C-dev --location japaneast
//
// For single-group workshops, leave groupId empty (default)
// =============================================================================
param groupId = ''  // Set to 'A'-'J' for multi-group workshops

// =============================================================================
// Microsoft Entra ID - Authentication Configuration
// =============================================================================
// These parameters configure authentication for both frontend and backend
// =============================================================================

// Microsoft Entra tenant ID (shared by all apps)
// Get with: az account show --query tenantId -o tsv
param entraTenantId = ''  // REQUIRED: Add your Entra tenant ID here

// Microsoft Entra client ID - Backend API (registered app)
// Get from Azure Portal > App registrations > Backend API > Application (client) ID
param entraBackendClientId = ''  // REQUIRED: Add your backend API client ID here

// Microsoft Entra client ID - Frontend SPA (registered app)
// Get from Azure Portal > App registrations > Frontend SPA > Application (client) ID
param entraFrontendClientId = ''  // REQUIRED: Add your frontend SPA client ID here

// =============================================================================
// Cosmos DB Configuration
// =============================================================================

// Cosmos DB admin password - use a strong password
// Generate with: openssl rand -base64 16
param cosmosDbAdminPassword = ''  // REQUIRED: Add Cosmos DB admin password

// =============================================================================
// Cost Optimization - Smaller SKUs for Development
// =============================================================================

// Use smallest App Service tier
param appServiceSku = 'B1'  // ~$13/month

// Use smallest Cosmos DB tier
param cosmosDbTier = 'M25'  // ~$100/month (vs M30 ~$200/month)

// Disable Cosmos DB HA (saves ~50%)
param cosmosDbEnableHa = false

// Standard tier for Static Web Apps (required for Linked Backend feature)
// Note: Free tier does NOT support Linked Backend
param staticWebAppSku = 'Standard'  // ~$9/month

// Static Web Apps location (not available in japaneast)
// Available regions: westus2, centralus, eastus2, westeurope, eastasia
param staticWebAppLocation = 'eastasia'  // Closest to Japan

// =============================================================================
// =============================================================================
// Architecture Notes
// =============================================================================
// This architecture uses SWA Linked Backend instead of Application Gateway:
// - Static Web Apps automatically routes /api/* to App Service
// - No SSL certificate management required
// - Simplified architecture with lower cost (~$250/month savings)
// - App Service is publicly accessible but protected by Entra ID auth
// =============================================================================
